### ISSUE TITLE
Property 'brand' does not exist on type IntrinsicAttributes

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun-frontend#1781]
## 💥 Regression Report

Seems to be an [incompatibility](https://github.com/HospitalRun/hospitalrun-frontend/pull/1776/checks?check_run_id=418840720) with new version 0.32.0 of components 

## Last working version

Worked up to version: 0.31.0

Stopped working in version: [0.32.0](https://github.com/HospitalRun/components/pull/228)

```js
TypeScript error in /home/travis/build/HospitalRun/hospitalrun-frontend/src/components/Navbar.tsx(12,7):

Type '{ brand: { label: string; onClick: () => void; }; search: { onClickButton: () => void; onChangeInput: () => void; placeholderText: string; buttonText: string; }; navLinks: { label: string; onClick: () => void; children: { ...; }[]; }[]; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "ref" | "className" | "children" | "navItems" | "key"> & Partial<Pick<Props, "bg" | "variant">> & Partial<...>'.

Property 'brand' does not exist on type 'IntrinsicAttributes & Pick<Props, "ref" | "className" | "children" | "navItems" | "key"> & Partial<Pick<Props, "bg" | "variant">> & Partial<...>'.  TS2322    
10 |   return (   
11 |     <HospitalRunNavbar  > 
12 |       brand={{       |       ^    
13 |         label: 'HospitalRun',    
14 |         onClick: () => {    
15 |           history.push('/')
```
